"""LLM-based signal: asks Groq to judge holistic semantic/stylistic coherence.

Captures a different property from the stylometric signal — meaning and
"voice" rather than surface statistics.
"""
import json
import os

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a content provenance analyst. Given a piece of text, judge how "
    "likely it is to have been generated by an AI language model versus "
    "written by a human. Consider generic phrasing, over-hedged or "
    "over-balanced tone, clichéd transitions (e.g. 'Furthermore', 'It is "
    "important to note'), and unnaturally even structure as signs of AI "
    "generation. Consider idiosyncratic voice, concrete specific detail, "
    "and irregular structure as signs of human writing.\n\n"
    "Respond with ONLY a JSON object of the exact form:\n"
    '{"ai_likelihood": <float between 0.0 and 1.0>, "reasoning": "<one short sentence>"}\n'
    "0.0 means certainly human-written, 1.0 means certainly AI-generated."
)

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError(
                "GROQ_API_KEY is not set. Add it to your .env file before "
                "calling the LLM signal."
            )
        _client = Groq(api_key=api_key)
    return _client


def analyze(text):
    client = _get_client()
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0.2,
    )
    raw = response.choices[0].message.content

    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_likelihood"])
        reasoning = str(parsed.get("reasoning", ""))
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise RuntimeError(f"Groq returned an unparseable response: {raw!r}") from exc

    score = max(0.0, min(1.0, score))
    return {"score": round(score, 4), "reasoning": reasoning}
